/*
	Si4x6x <-> ATmega328P
		NSEL	PB2 (SS)
		SDI		PB3 (MOSI)
		SDO		PB4 (MISO)
		SCLK	PB5 (SCK)
		
		GPIO0	PD2 (INT0 - external interrupt)		CTS (output) - HIGH when able to receive
		GPIO1	PD3 (INT1 - external interrupt)		TX_DATA_CLK (output) - for use in TX Direct Synchronous Mode
		GPIO2	PB0									INPUT (input) - TXDATA for TX Direct Mode
		GPIO3	PD7									TRISTATE - input and output drivers disabled
		
		SDN		PB1 (LOW - IC active, HIGH - IC shutdown)
		VTCXO	PD6 (if used)
	
	Si4x6x Reference (Xin pin)
		Timepulse	needs setting up via the GNSS module
		TCXO		needs power via PD6
	
	A single high precision local oscillator (LO) is used for transmit mode. The LO is generated by an integrated VCO
	and ?? Fractional-N PLL synthesizer. The synthesizer is designed to support configurable data rates from 100 bps
	to 1 Mbps.
	
	Frequency Bands		Resolution		Modulation Range
	142-175MHz			4.7Hz			250kHz
	283–350MHz			9.5Hz			500kHz
	420–525MHz			14.3Hz			750kHz
	850–1050MHz			28.6Hz			1.5MHz
	
	The transmit FSK data is modulated directly into the ??	data stream and can be shaped by a Gaussian low-pass filter
	to reduce unwanted spectral content.
*/


#ifndef AVR_SI4X6X_H
#define AVR_SI4X6X_H


#include <avr/io.h>
#include <avr/interrupt.h>
#include <util/delay.h>
#include "AVR_SPI.h"
#include "AVR_TC.h"
#include "AVR_WDT.h"


// Functions
void SI4X6X_init(uint32_t ref_freq, uint8_t tcxo);
void SI4X6X_deinit(uint8_t tcxo);
void SI4X6X_rx_CTS(uint8_t * rx_buffer, uint8_t len);
void SI4X6X_check_CTS(void);
void SI4X6X_setup_pins(uint8_t gpio0, uint8_t gpio1, uint8_t gpio2, uint8_t gpio3, uint8_t nirq, uint8_t sdo);
void SI4X6X_change_state(uint8_t state);
void SI4X6X_start_TX(uint8_t channel);
void SI4X6X_get_part_info(uint8_t * buffer);
void SI4X6X_get_func_info(uint8_t * buffer);
uint16_t SI4X6X_get_temperature(void);
void SI4X6X_set_frequency(uint32_t frequency, uint32_t ref_freq);
void SI4X6X_set_frequency_deviation(uint32_t deviation);
void SI4X6X_set_frequency_offset(uint32_t offset);
void SI4X6X_set_modulation(uint8_t mod, uint8_t async);
void SI4X6X_set_data_rate(uint32_t data_rate, uint8_t txosr);
void SI4X6X_set_PA_mode(uint8_t pa_sel, uint8_t pa_mode);
void SI4X6X_set_power_level(uint8_t level);
void SI4X6X_set_filter_coefficients(void);
void SI4X6X_tx_CW_blips(uint32_t count, uint16_t length_ms, uint32_t frequency, uint32_t ref_freq, uint16_t modem_freq_offset);
void SI4X6X_tx_FSK_rtty(uint8_t * packet, uint8_t length, uint16_t baud, uint32_t frequency,
						uint32_t ref_freq, uint16_t modem_freq_dev, uint16_t modem_freq_offset);
void SI4X6X_tx_GFSK_aprs(uint8_t * bitstream, uint16_t length, uint32_t frequency, uint32_t ref_freq, uint16_t modem_freq_offset);


#endif // AVR_SI4X6X_H_